apiVersion: v1
kind: Service
metadata:
  name: graphql-demo-service
  namespace: graphql-demo
spec:
  selector:
    app: graphql-demo-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
